### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by erickjx** [skandasoft/hide-tree#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: "openSUSE 13.2
**Thrown From**: [hide-tree](https://github.com/skandasoft/hide-tree) package, v0.0.4
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/user/.atom/packages/hide-tree/lib/hide-tree-view.coffee:38

TypeError: Cannot read property '0' of undefined
    at HTMLSpanElement.<anonymous> (/home/user/.atom/packages/hide-tree/lib/hide-tree-view.coffee:84:52)
    at HTMLSpanElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -5:10 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner-css, v1.2.0
atom-html-preview, v0.1.8
autocomplete-php, v0.3.6
browser-plus, v0.0.23
build, v0.38.0
clipboard-plus, v0.5.0
color-picker, v2.0.7
git-log, v0.4.1
hide-tree, v0.0.4
language-doxygen, v0.2.1
language-freemarker, v0.2.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-log, v0.4.0
linter-csslint, v0.0.14
linter-tidy, v1.0.1
linter-xmllint, v0.0.6
log-console, v0.2.0
minimap, v4.10.0
navigate, v0.1.6
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by mrmechko** [comment]
I clicked the little orange square at the bottom and got this error.

**Comment by skandasoft** [comment]
@erickjx I am not sure why it would be caused ..but i added additonal checks...check out the latest...

@mrmechko - not sure on the orange square..but you can always try the  updated version..

**Comment by mrmechko** [comment]
![orangesquare](https://cloud.githubusercontent.com/assets/1429154/8599527/03c06874-262f-11e5-8a54-79c4def18d5c.png)

Updated to latest package. clicking the little square indicated by the huge red wedge still procs this error.  Not a fatal issue, but still it persists.

**Comment by skandasoft** [comment]
I will check on the uncaught error...but wondering so you don't get the arrow thing/lock icon...? does it mean ociticon doesn't come with atom.

**Comment by mrmechko** [comment]
Ah I was wondering if that was a missing icon.  I know octicons are used by atom in other packages (e.g. `flex-toolbar`)

**Comment by skandasoft** [comment]
fixed the error throw.in the latest version...but check about the octicon...if you can do something about..nobody else reported..

feel free to reopen if it doesn't resolve

**Comment by skandasoft** [comment]
I added octicon to the styles..so you should have a problem seeing the icons..Please report in case you still don't see it.

**Comment by skandasoft** [comment]
I found the issue for the octicons...Mine was working because I had loaded another package..now with the latest fix..it is solved..
